version: "3.9"

services:
  mongodb:
    image: mongo:4.2
    container_name: "payments_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      #- MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      #- MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./volumes/data/db:/data/db
    ports:
      - 27020:27017
    command: mongod --bind_ip_all --logpath=/dev/null
  ms_payments:
    build:
      context: .
    image: mijoco/ms_payments
    container_name: "ms_payments"
    environment:
      - spring.profiles.active=${spring_profiles_active}
      - GITHUB_PAT=${GITHUB_PAT}
      - JAVA_OPTS=-Xm2g -Xms2g
    ports:
      - "8404:8104"
      - "8405:8080"
    links:
      - mongodb