spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 544ed67fb1388bed1d75
            clientSecret: e934104770bceae1aa57ad85d42d5c647415a2a2
stacks:
   dao:
      deployer: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
opennode:
   api:
      apiEndpoint: https://dev-api.opennode.com
      appEndpoint: https://dev.opennode.com
      callbackUrl: https://tapi.brightblock.org/mesh/v2/charge/callback
sendinblue:
   api:
      adminEmail: info@electricart.gallery
      linkAdminRequest: https://staging.stacksmate.com/mgmnt/exhibit-requests
      linkUserSubcribes: https://staging.stacksmate.com/mgmnt/subscribe
      emailTemplate1Url: https://staging.electricart.gallery/Email.html
      emailTemplate1: EmailTemplate1.html
      key: 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
mandrill:
   api:
      key: 9Pk36qtppNlJeeWdqClyeQ
squareup:
   api:
      applicationName: rpay-prom
      redirectUrl: https://tapi.risidio.com/mesh/oauth-redirect
radicle:
   security:
      enable-csrf: false
   gaia:
      huburl: https://core.blockstack.org/v1/users/
   search:
      indexurl: http://docker.for.mac.localhost:8048/index/indexMetaData/
   mongo:
      mongoIp: mongodb://mongodb
      mongoPort: 27017
      mongoDbName: mesh
   stx-mining:
      mining-path: http://monitor.stxmining.xyz/mining_info
   binance:
      rate-path: https://api.binance.com/api/v3/ticker/24hr
      fiat-list: GBP,USD,EUR,AUD,JPY,HKD
   ticker:
      rate-path: https://blockchain.info/ticker
   btcfee:
      fee-rate: https://bitcoinfees.earn.com/api/v1/fees/recommended
      fee-list: https://bitcoinfees.earn.com/api/v1/fees/list
   stax:
      base-path: http://docker.for.mac.localhost:20443
      blockchain-api-path: http://docker.for.mac.localhost:3999
      stacks-path: http://localhost:20443
      admin-contract-address: ST1ESYCGJB5Z5NBHS39XPC70PGC14WAQK5XXNQYDW
      admin-contract-name: appmap-v1
      stacksmate: http://docker.for.mac.localhost:8108
cloudinary:
   cloudName: mijo-enterprises
   baseDeliveryUrl: http://res.cloudinary.com/mijo-enterprises
   secureDeliveryUrl: https://res.cloudinary.com/mijo-enterprises
   apiBaseUrl: https://api.cloudinary.com/v1_1/mijo-enterprises

---

spring:
   profiles: test
application:
   mongoIp: mongodb://localhost
radicle:
   stax:
      base-path: http://176.58.109.133:20443
      blockchain-api-path: http://176.58.109.133:3999

---

spring:
    profiles: linux-dev
application:
   mongoIp: mongodb://localhost
radicle:
   stax:
      base-path: http://172.17.0.1:20443
      blockchain-api-path: http://172.17.0.1:3999

---

spring:
    profiles: docker-dev
application:
   mongoIp: mongodb://localhost
radicle:
   stax:
      base-path: http://176.58.109.133:20443
      blockchain-api-path: http://176.58.109.133:3999

---

spring:
    profiles: staging
application:
   mongoIp: mongodb://mongodb
   mongoPort: 27017
squareup:
   api:
      applicationName: rpay-prom
      redirectUrl: https://tapi.risidio.com/mesh/oauth-redirect
stacks:
   dao:
      deployer: ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT
radicle:
   search:
      indexurl: http://176.58.109.133:8048/index/indexMetaData/
   stax:
      base-path: http://176.58.109.133:20443
      blockchain-api-path: http://176.58.109.133:3999
      stacks-path: https://stacks-node-api.testnet.stacks.co
      admin-contract-address: ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT
      admin-contract-name: appmap-v1
      stacksmate: http://stacksmate:8080

---

spring:
    profiles: production
application:
   mongoIp: mongodb://mongodb
   mongoPort: 27017
sendinblue:
   api:
      emailTemplate1Url: https://electricart.gallery/Email.html
      linkAdminRequest: https://stacksmate.com/mgmnt/exhibit-requests
      linkUserSubcribes: https://stacksmate.com/mgmnt/subscribe
squareup:
   api:
      applicationName: rpay-prom
      redirectUrl: https://api.risidio.com/mesh/oauth-redirect
opennode:
   api:
      apiEndpoint: https://api.opennode.com
      appEndpoint: https://app.opennode.com
      callbackUrl: https://api.brightblock.org/mesh/v2/charge/callback
stacks:
   dao:
      deployer: SP3BTM84FYABJGJ83519GG5NSV0A6A13D4NHJSS32
radicle:
   search:
      indexurl: http://172.17.0.1:8048/index/indexMetaData/
   stax:
      base-path: http://45.79.131.55:20443
      blockchain-api-path: http://45.79.131.55:3999
      stacks-path: https://stacks-node-api.mainnet.stacks.co
      admin-contract-address: SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ
      admin-contract-name: appmap-v1
      stacksmate: http://stacksmate:8080
   